// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MigrationCreator
{
    internal sealed partial class Vsix
    {
        public const string Id = "MigrationCreator.b6bb2fc5-25fe-4344-9f44-2faf322c30b4";
        public const string Name = "MigrationCreator";
        public const string Description = @"Расширение упрощает создание миграции для ESevices";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Pozdeev Kirill";
        public const string Tags = "";
    }
}
